---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # install latest
  - ansible-galaxy install git+https://github.com/stoe/ansible-role-ghe-upgrade-simple,${TRAVIS_PULL_REQUEST_SHA} -f
  # Lint the role incl. tasks, handlers, meta
  - ansible-lint tests/test.yml
  # Check role syntax
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
