---
language: python
python:
  - "2.7"
  - "3"

matrix:
  fast_finish: true
  allow_failures:
    - python: "3"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Install latest role version (from PR)
  - ansible-galaxy install -f -p "tests/" "git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_PULL_REQUEST_SHA}"
  # Lint the role incl. tasks, handlers, meta
  - ansible-lint tests/test.yml
  # Check role syntax
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
